// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using printing_calculator;

#nullable disable

namespace printing_calculator.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230907093606_addCrm")]
    partial class addCrm
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("printing_calculator.DataBase.СalculationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("ConsumablePriceId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreasingPrice")
                        .HasColumnType("integer");

                    b.Property<int?>("CutPrice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DrillingPrice")
                        .HasColumnType("integer");

                    b.Property<int>("InputId")
                        .HasColumnType("integer");

                    b.Property<int?>("LaminationMarkup")
                        .HasColumnType("integer");

                    b.Property<float?>("LaminationPrices")
                        .HasColumnType("real");

                    b.Property<int?>("MarkupPaper")
                        .HasColumnType("integer");

                    b.Property<float>("PaperPrice")
                        .HasColumnType("real");

                    b.Property<int?>("Price")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("RoundingPrice")
                        .HasColumnType("integer");

                    b.Property<int?>("SpringBrochurePrice")
                        .HasColumnType("integer");

                    b.Property<int?>("StapleBrochurePrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConsumablePriceId");

                    b.HasIndex("InputId");

                    b.HasIndex("ProductId");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("printing_calculator.DataBase.ConsumablePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DrumPrice1")
                        .HasColumnType("integer");

                    b.Property<int>("DrumPrice2")
                        .HasColumnType("integer");

                    b.Property<int>("DrumPrice3")
                        .HasColumnType("integer");

                    b.Property<int>("DrumPrice4")
                        .HasColumnType("integer");

                    b.Property<int>("TonerPrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ConsumablePrices");
                });

            modelBuilder.Entity("printing_calculator.DataBase.crm.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("printing_calculator.DataBase.crm.Mail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Mails");
                });

            modelBuilder.Entity("printing_calculator.DataBase.crm.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("printing_calculator.DataBase.crm.PhoneNmber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("PhoneNmbers");
                });

            modelBuilder.Entity("printing_calculator.DataBase.crm.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivecalculationHistoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("printing_calculator.DataBase.InputHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<List<string>>("CommonToAllMarkupName")
                        .HasColumnType("text[]");

                    b.Property<int>("CreasingAmount")
                        .HasColumnType("integer");

                    b.Property<int>("DrillingAmount")
                        .HasColumnType("integer");

                    b.Property<bool>("Duplex")
                        .HasColumnType("boolean");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Kinds")
                        .HasColumnType("integer");

                    b.Property<int?>("LaminationId")
                        .HasColumnType("integer");

                    b.Property<int>("PaperId")
                        .HasColumnType("integer");

                    b.Property<bool>("RoundingAmount")
                        .HasColumnType("boolean");

                    b.Property<int>("SpringBrochure")
                        .HasColumnType("integer");

                    b.Property<bool>("StapleBrochure")
                        .HasColumnType("boolean");

                    b.Property<int>("Whidth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LaminationId");

                    b.HasIndex("PaperId");

                    b.ToTable("InputsHistories");
                });

            modelBuilder.Entity("printing_calculator.DataBase.Lamination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Laminations");
                });

            modelBuilder.Entity("printing_calculator.DataBase.PaperCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("PaperThickness")
                        .HasColumnType("real");

                    b.Property<float>("Prices")
                        .HasColumnType("real");

                    b.Property<int>("SizeId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SizeId");

                    b.ToTable("PaperCatalogs");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.CommonToAllMarkup", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int>("Adjustmen")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PercentMarkup")
                        .HasColumnType("integer");

                    b.Property<int?>("SettingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SettingId");

                    b.ToTable("CommonToAllMarkups");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.MachineSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdjustmenPrice")
                        .HasColumnType("integer");

                    b.Property<float>("ConsumableOther")
                        .HasColumnType("real");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameMachine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SettingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NameMachine")
                        .IsUnique();

                    b.HasIndex("SettingId");

                    b.ToTable("MachineSettings");

                    b.HasDiscriminator<string>("Discriminator").HasValue("MachineSetting");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.Markup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MachineSettingId")
                        .HasColumnType("integer");

                    b.Property<int>("MarkupForThisPage")
                        .HasColumnType("integer");

                    b.Property<int>("Page")
                        .HasColumnType("integer");

                    b.Property<int?>("SpringBrochureSettingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MachineSettingId");

                    b.HasIndex("SpringBrochureSettingId");

                    b.ToTable("Markups");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.SpringBrochureSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoverCardboardA3Price")
                        .HasColumnType("integer");

                    b.Property<int>("CoverCardboardA4Price")
                        .HasColumnType("integer");

                    b.Property<int>("CoverPlasticA3Price")
                        .HasColumnType("integer");

                    b.Property<int>("CoverPlasticA4Price")
                        .HasColumnType("integer");

                    b.Property<int>("PriceForA3")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SpringBrochureSettings");
                });

            modelBuilder.Entity("printing_calculator.DataBase.SizePaper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SizePapers");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.PosMachinesSetting", b =>
                {
                    b.HasBaseType("printing_calculator.DataBase.setting.MachineSetting");

                    b.Property<float>("AddMoreHit")
                        .HasColumnType("real");

                    b.Property<int>("CountOfPapersInOneAdjustmentCut")
                        .HasColumnType("integer");

                    b.Property<int?>("SettingId1")
                        .HasColumnType("integer");

                    b.HasIndex("SettingId1");

                    b.HasDiscriminator().HasValue("PosMachinesSetting");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.PrintingMachineSetting", b =>
                {
                    b.HasBaseType("printing_calculator.DataBase.setting.MachineSetting");

                    b.Property<int>("Bleed")
                        .HasColumnType("integer");

                    b.Property<int>("ConsumableDye")
                        .HasColumnType("integer");

                    b.Property<int>("FieldForLabels")
                        .HasColumnType("integer");

                    b.Property<int>("MainConsumableForDrawing")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumSizeLength")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumSizeWidth")
                        .HasColumnType("integer");

                    b.Property<int?>("SettingId1")
                        .HasColumnType("integer")
                        .HasColumnName("PrintingMachineSetting_SettingId1");

                    b.Property<float>("WhiteFieldHeight")
                        .HasColumnType("real");

                    b.Property<float>("WhiteFieldWidth")
                        .HasColumnType("real");

                    b.HasIndex("SettingId1");

                    b.HasDiscriminator().HasValue("PrintingMachineSetting");
                });

            modelBuilder.Entity("printing_calculator.DataBase.СalculationHistory", b =>
                {
                    b.HasOne("printing_calculator.DataBase.ConsumablePrice", "ConsumablePrice")
                        .WithMany()
                        .HasForeignKey("ConsumablePriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("printing_calculator.DataBase.InputHistory", "Input")
                        .WithMany()
                        .HasForeignKey("InputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("printing_calculator.DataBase.crm.Product", null)
                        .WithMany("Histories")
                        .HasForeignKey("ProductId");

                    b.Navigation("ConsumablePrice");

                    b.Navigation("Input");
                });

            modelBuilder.Entity("printing_calculator.DataBase.crm.Contact", b =>
                {
                    b.HasOne("printing_calculator.DataBase.crm.Order", null)
                        .WithMany("Contacts")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("printing_calculator.DataBase.crm.Mail", b =>
                {
                    b.HasOne("printing_calculator.DataBase.crm.Contact", "Contact")
                        .WithMany("Mails")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("printing_calculator.DataBase.crm.PhoneNmber", b =>
                {
                    b.HasOne("printing_calculator.DataBase.crm.Contact", "Contact")
                        .WithMany("PhoneNmbers")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("printing_calculator.DataBase.crm.Product", b =>
                {
                    b.HasOne("printing_calculator.DataBase.crm.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("printing_calculator.DataBase.InputHistory", b =>
                {
                    b.HasOne("printing_calculator.DataBase.Lamination", "Lamination")
                        .WithMany()
                        .HasForeignKey("LaminationId");

                    b.HasOne("printing_calculator.DataBase.PaperCatalog", "Paper")
                        .WithMany()
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lamination");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("printing_calculator.DataBase.PaperCatalog", b =>
                {
                    b.HasOne("printing_calculator.DataBase.SizePaper", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Size");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.CommonToAllMarkup", b =>
                {
                    b.HasOne("printing_calculator.DataBase.setting.Setting", null)
                        .WithMany("CommonToAllMarkups")
                        .HasForeignKey("SettingId");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.MachineSetting", b =>
                {
                    b.HasOne("printing_calculator.DataBase.setting.Setting", null)
                        .WithMany("Machines")
                        .HasForeignKey("SettingId");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.Markup", b =>
                {
                    b.HasOne("printing_calculator.DataBase.setting.MachineSetting", null)
                        .WithMany("Markups")
                        .HasForeignKey("MachineSettingId");

                    b.HasOne("printing_calculator.DataBase.setting.SpringBrochureSetting", null)
                        .WithMany("SpringPrice")
                        .HasForeignKey("SpringBrochureSettingId");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.PosMachinesSetting", b =>
                {
                    b.HasOne("printing_calculator.DataBase.setting.Setting", null)
                        .WithMany("PosMachines")
                        .HasForeignKey("SettingId1");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.PrintingMachineSetting", b =>
                {
                    b.HasOne("printing_calculator.DataBase.setting.Setting", null)
                        .WithMany("PrintingsMachines")
                        .HasForeignKey("SettingId1");
                });

            modelBuilder.Entity("printing_calculator.DataBase.crm.Contact", b =>
                {
                    b.Navigation("Mails");

                    b.Navigation("PhoneNmbers");
                });

            modelBuilder.Entity("printing_calculator.DataBase.crm.Order", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("printing_calculator.DataBase.crm.Product", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.MachineSetting", b =>
                {
                    b.Navigation("Markups");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.Setting", b =>
                {
                    b.Navigation("CommonToAllMarkups");

                    b.Navigation("Machines");

                    b.Navigation("PosMachines");

                    b.Navigation("PrintingsMachines");
                });

            modelBuilder.Entity("printing_calculator.DataBase.setting.SpringBrochureSetting", b =>
                {
                    b.Navigation("SpringPrice");
                });
#pragma warning restore 612, 618
        }
    }
}
